### ISSUE TITLE
Convert to idempotent transaction

### ISSUE THREAD

**Issue by EasonLiao** [zk1931/pulsefs#17]
I'm thinking how to convert request to idempotent transactions, since for each update on StateMachine we'll bump version all the way up to root node, so we can use the version of root node as the source of truth.

We attach the current version of root node to each transaction in `preprocess` and execute the transaction if and only if the version of txn matches the version of root in `deliver`. I feel this will simplify the implementation somehow.

@m1ch1  Do you think it makes sense?

**Comment by ghost** [comment]
could you give me examples where the version in the txn doesn't match the verson in deliver?

**Comment by EasonLiao** [comment]
For example, at beginning the version of root is 0, now we gonna create first child node, in preprocess we attach the version of root, which is 0 to the txn.

If this txn has been delivered in state machine and we re-execute it, we find the version of root is 1 and the version of txn is 0, so we won't execute it.

If this txn hasn't been delivered, we find the version of txn matches the version of root, then we execute it.

**Comment by EasonLiao** [comment]
Another problem came up in my mind is that user can do conditional operation, for example, set the data of a node if the node has version X.

Actually we can find out whether this operation will succeed or not just in `preprocess` callback, if we find the operation will fail we can just reply user directly. Now since we find the operation will fail, we actually can choose do not broadcast this command since it makes no sense to persist it to disk, but for not Jzab has no support to this.

**Comment by ghost** [comment]
what does zookeeper do? this might be a nice optimization to add depending on how frequent version check failures are.

for attaching the root version to txn, does this mean the operation fails if there is a pending txn? i'm not quite getting what's being simplified. lets' talk about this tomorrow.

**Comment by EasonLiao** [comment]
We'll also take the pending txn into consideration, like have something like "pre-applied" root version.

I'm not sure what zookeeper does, we can discuss it tomorrow.

**Comment by ghost** [comment]
somewhat related discussion: https://issues.apache.org/jira/browse/ZOOKEEPER-1092

**Comment by ghost** [comment]
also https://issues.apache.org/jira/browse/ZOOKEEPER-1285 discusses something similar to what you were suggesting today. concurrent reads and writes without locking and consistent snapshots. maybe worth considering?

**Comment by ghost** [comment]
anything to do here?

**Comment by EasonLiao** [comment]
I think we can get rid of the requirement of idempotency since the snapshot is always consistent. We only  need to include the last delivered zxid in snapshot. After recovery, we only apply the transactions after last delivered zxid after snapshot. It sounds right, but I'll think more about details.

**Comment by EasonLiao** [comment]
I'll think it more tomorrow and write a detailed proposal here.

**Comment by EasonLiao** [comment]
I think it's OK to write the last zxid applied to the root DataTree at the time of snapshot to snapshot file. After recovery, we just ignore all the transaction after this zxid, then we can get rid of idempotency requirement.  Like what I described at https://github.com/zk1931/jzab/pull/209

**Comment by ghost** [comment]
i guess you mean to ignore all the transactions before and including this zxid?

**Comment by EasonLiao** [comment]
yes, that's what i'm thinking
