### ISSUE TITLE
Directory doesn't store data?

### ISSUE THREAD

**Issue by EasonLiao** [zk1931/pulsefs#19]
In SPEC if you want to list files under dir we do : 

```
GET /foo/bar/dir HTTP/1.1

HTTP/1.1 200 OK
version: 2

{
  "contents": [
    {
      "path": "/foo/bar/dir/0000000000000001",
      "type": "file"
      "version": 0
    },
    {
      "path": "/foo/bar/dir/0000000000000002",
      "type": "file"
      "version": 0
    }
  ]
}
```

This will return all files/directories under the directory not data of the directory, so I assume directory doesn't store data?

**Comment by ghost** [comment]
That's what I'm thinking. I'm trying to keep it similar to how file systems look like.
