### ISSUE TITLE
Make /pulsed directory part of the tree

### ISSUE THREAD

**Issue by EasonLiao** [zk1931/pulsefs#59]
Like what we discussed before, the /pulsed directory has been reserved for special purpose (stores cluster configuration, session files, pulsed version, etc.). What I can imagine is : 

```
/pulsed/servers : stores cluster configuration
/pulsed/session : stores session files
/pulsed/config : stores configuration of each server, for example, /pulsed/config/server1
 can store configurations about server1, like cpu, memory, etc.
```

It would be good we can store all the information in the tree instead of handling them specially, in this case user can access these information in the same way as other nodes of the tree, this is more consistent. 

Another benefit I can imagine is user can watch the cluster configuration change by watching `/pulsed/servers` directory, once it's changed, users can update their cluster member list.

The only difference is user can not modify this special directory whatever they want, for example, they can't create a file under /pulsed/servers directory. This is easy to do if we just use different servlet with limited access to tree.

Another problem is /pulsed/servers directory, we can't update this directory just in `leading` and `following` callback because this might make the tree inconsistent. Instead, the leader should explicitly broadcast `activeFollowers` and `clusterMembers` in its leading callback so this will make cluster/membership change consistent across all the servers.

**Comment by ghost** [comment]
why would updating the tree in leading/following callbacks make the tree inconsistent?

**Comment by EasonLiao** [comment]
First if a node recovers or dies leading and following callback will be called, and these events will not be recorded in log, so different server might have different views. 

Even the COP is recorded in log, but since new joined server will not be delivered every COP in history, it will only be delivered the last COP in log, so different servers might receive different sequences of COP.

**Comment by ghost** [comment]
ok that makes sense. could you first update the api spec so that we know how it's going to look like?

**Comment by EasonLiao** [comment]
Sure will do.

**Comment by EasonLiao** [comment]
updated api spec in #60

**Comment by EasonLiao** [comment]
I think this one can be closed
