### ISSUE TITLE
How to create a ephemeral file

### ISSUE THREAD

**Issue by EasonLiao** [zk1931/pulsefs#62]
I'm imaging it's like `PUT /bar/fool/file1&session=ID`, right?

**Comment by EasonLiao** [comment]
Also I'm thinking that if PUT has a session field then it implies that `version == -1`(create a file), since it doesn't make sense to update a file with a session parameter

**Comment by ghost** [comment]
i don't think we need to treat ephemeral files differently from regular files. The only difference is that when an file is created with ephemeral flag, it remembers the session id, and it gets deleted when the session expires. 

i'm guessing that some applications will include the session id in all the requests, so it might be better to put it in the header. how about something like this:

```
# create a session
POST /pulsed/session HTTP/1.1

HTTP/1.1 201 Created
content-length: 0
location: /pulsed/session/0000000000000000
timeout-sec: 10

# send a pulse
PUT /pulsed/session/0000000000000000 HTTP/1.1

HTTP/1.1 200 Ok
content-length: 0
location: /pulsed/session/0000000000000000
timeout-sec: 10

# create a new file
PUT /newfile?ephemeral HTTP/1.1
content-length: 13
session: 0000000000000000

Hello, world!

HTTP/1.1 201 Created
version: 0
content-length: 0

# get a file with session id specified
GET /newfile HTTP/1.1
session: 0000000000000000

HTTP/1.1 200 Ok
version: 0
content-length: 13
owner: 0000000000000000

Hello, world!

# explicitly delete a session
# send a pulse
DELETE /pulsed/session/0000000000000000 HTTP/1.1

HTTP/1.1 204 No Content

# once you delete the session, any request made with the session id will fail.
GET /newfile HTTP/1.1
session: 0000000000000000

HTTP/1.1 403 Session 0000000000000000 does not exist
```

**Comment by ghost** [comment]
or maybe `PUT /newfile?ephemeral&session=0000000000000000 HTTP/1.1`?

**Comment by EasonLiao** [comment]
I get your point, you mean the user might attach session id field in every request so we can't decide whether to create ephemeral file or regular file by just looking at the session field. The user must explicitly attach ephemeral flag in request, otherwise we treat them as regular file.

I'm OK with either put the session id in header or query string.  However, I'm not sure if I understand right or not, I don't think the regular file should contain session field since every time the client starts they need to get a new session id, if every file/dir contains session id then eventually these session ids will just be dead sessions. I feel only ephemeral files should contain session id.

**Comment by EasonLiao** [comment]
Which means the session id is just for ephemeral file but if you want to create ephemeral file you must explicitly specify both session id and ephemeral flag.

**Comment by ghost** [comment]
right, only the ephemeral files have the 'owner' field, but the client should be able to send requests with the session id specified. otherwise the client can't say 'do this only if my session is active'.

let's put the session id in the query string for now like `PUT /newfile?ephemeral&session=0000000000000000 HTTP/1.1`.

another question is whether we want to zero-pad session ids. it makes session ids longer but the directory listing of `/pulsed/sessions` will be sorted, which is kind of nice.

**Comment by EasonLiao** [comment]
It sounds great to have features like "do this only if my session is active"

Sounds good to put the session id in query. I'm not sure whether we want zero-pad session ids, probably we store zero-pad session ids under /pulsed/sessions, but user can just attach either the non-zero-pad session ids or zero-ad session ids in request.

**Comment by ghost** [comment]
ok let's keep session ids non-padded for now.
